import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Activity, AlertTriangle, ArrowLeft, ArrowRight, Bell, Building2, CalendarDays, Camera, Check, CheckCircle2, ChevronDown, CircleDollarSign, Clock3, Copy, FileCheck2, FileText, Handshake, LayoutDashboard, ListFilter, LockKeyhole, Mail, Menu, Mic, MicOff, MoreHorizontal, Pause, PenLine, Play, Plus, Redo2, Search, Send, Settings, ShieldCheck, Sparkles, StopCircle, Trash2, Undo2, UserRound, Users, Video, VideoOff, WalletCards, X } from "lucide-react";
import { agreements, deals, milestones, money, organisation, transcript as initialTranscript } from "@/data/mock";
import type { Deal, DealStatus, Transcript } from "@/types/armor";
import { Button, Card, Field, IconButton, Modal, Progress, StatusBadge } from "./armor-ui";

type Screen="dashboard"|"new"|"meeting"|"recording"|"transcript"|"analysis"|"review"|"agreement"|"counterparty"|"deal"|"deals"|"agreements"|"activity"|"settings"|"login"|"signup";
const nav=[{id:"dashboard",label:"Dashboard",icon:LayoutDashboard},{id:"new",label:"New Conversation",icon:Plus},{id:"deals",label:"Deals",icon:Handshake},{id:"agreements",label:"Agreements",icon:FileCheck2},{id:"activity",label:"Activity",icon:Activity},{id:"settings",label:"Settings",icon:Settings}] as const;
const titles:Record<Screen,string>={dashboard:"Dashboard",new:"New Conversation",meeting:"Online Conversation",recording:"Offline Recording",transcript:"Conversation Transcript",analysis:"Deal Analysis",review:"Review Deal Agreement",agreement:"Agreement",counterparty:"Agreement Review",deal:"Deal Workspace",deals:"Deals",agreements:"Agreements",activity:"Activity",settings:"Organisation Settings",login:"Sign in",signup:"Create organisation"};

export default function ArmorApp(){
 const [screen,setScreen]=useState<Screen>("dashboard"),[sidebar,setSidebar]=useState(false),[modal,setModal]=useState<"end"|"send"|"resolve"|"notifications"|null>(null),[toast,setToast]=useState(""),[loading,setLoading]=useState(false),[search,setSearch]=useState(""),[selectedDeal,setSelectedDeal]=useState(deals[0]),[transcript,setTranscript]=useState(initialTranscript),[agreementStatus,setAgreementStatus]=useState<DealStatus>("Awaiting Counterparty");
 const go=(s:Screen)=>{setScreen(s);setSidebar(false);window.scrollTo(0,0)};
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2800)};
 const processEnd=()=>{setLoading(true);setTimeout(()=>{setLoading(false);setModal(null);go("transcript");notify("Conversation processed successfully.")},1500)};
 if(screen==="login"||screen==="signup") return <Auth screen={screen} go={go} notify={notify}/>;
 if(screen==="counterparty") return <Counterparty status={agreementStatus} setStatus={setAgreementStatus} go={go} notify={notify}/>;
 return <div className="app-shell">
  <Sidebar screen={screen} go={go} open={sidebar}/>
  <div className="app-main"><Header title={titles[screen]} setSidebar={setSidebar} setModal={setModal} go={go} search={search} setSearch={setSearch}/>
   <main className="page-wrap">
    {screen==="dashboard"&&<Dashboard go={go} openDeal={(d)=>{setSelectedDeal(d);go("deal")}}/>}
    {screen==="new"&&<NewConversation go={go}/>} {screen==="meeting"&&<Meeting onEnd={()=>setModal("end")}/>} {screen==="recording"&&<Recording go={go}/>} 
    {screen==="transcript"&&<TranscriptWorkspace rows={transcript} setRows={setTranscript} go={go} notify={notify}/>} {screen==="analysis"&&<Analysis go={go} onResolve={()=>setModal("resolve")}/>} {screen==="review"&&<DealReview go={go} notify={notify}/>} 
    {screen==="agreement"&&<Agreement go={go} onSend={()=>setModal("send")}/>} {screen==="deal"&&<DealDetail deal={selectedDeal}/>} {screen==="deals"&&<DealsDirectory query={search} openDeal={(d)=>{setSelectedDeal(d);go("deal")}}/>}
    {screen==="agreements"&&<Agreements notify={notify} go={go}/>} {screen==="activity"&&<ActivityCenter/>} {screen==="settings"&&<SettingsPage notify={notify}/>} 
   </main>
  </div>
  {modal==="end"&&<Modal title="End this conversation?" description="Armor will process the conversation and prepare the deal information." onClose={()=>setModal(null)}><div className="modal-actions"><Button variant="secondary" onClick={()=>setModal(null)}><X size={16}/>Cancel</Button><Button variant="danger" loading={loading} onClick={processEnd}><StopCircle size={16}/>End & Process Conversation</Button></div></Modal>}
  {modal==="send"&&<SendModal onClose={()=>setModal(null)} onSend={()=>{setModal(null);notify("Agreement sent successfully.")}}/>}
  {modal==="resolve"&&<ResolveModal onClose={()=>setModal(null)} onDone={()=>{setModal(null);notify("Delivery date verified.")}}/>}
  {modal==="notifications"&&<NotificationPanel onClose={()=>setModal(null)} go={go}/>} {toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}
 </div>
}

function Sidebar({screen,go,open}:{screen:Screen;go:(s:Screen)=>void;open:boolean}){return <aside className={`sidebar ${open?"sidebar--open":""}`}><button className="brand" onClick={()=>go("dashboard")}><span className="brand__mark"><ShieldCheck/></span><span>ARMOR</span></button><p className="nav-label">Workspace</p><nav>{nav.map(item=>{const I=item.icon;return <button key={item.id} className={screen===item.id?"active":""} onClick={()=>go(item.id)}><I size={18}/><span>{item.label}</span>{item.id==="agreements"&&<b>3</b>}</button>})}</nav><div className="sidebar__foot"><div className="org-avatar">VC</div><div><strong>Vertex Commerce</strong><span>Enterprise workspace</span></div><ChevronDown size={16}/></div></aside>}
function Header({title,setSidebar,setModal,go,search,setSearch}:{title:string;setSidebar:(v:boolean)=>void;setModal:(v:"notifications")=>void;go:(s:Screen)=>void;search:string;setSearch:(v:string)=>void}){return <header className="topbar"><div className="topbar__title"><IconButton label="Open navigation" className="menu-button" onClick={()=>setSidebar(true)}><Menu/></IconButton><div><span className="crumb">Armor / Workspace</span><h1>{title}</h1></div></div><div className="topbar__tools"><label className="global-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search deals, agreements, companies..."/></label><IconButton label="Notifications" onClick={()=>setModal("notifications")}><Bell size={19}/><i/></IconButton><Button onClick={()=>go("new")}><Plus size={17}/>New Conversation</Button><button className="profile"><span>RJ</span><ChevronDown size={15}/></button></div></header>}
function PageHeading({eyebrow,title,body,action}:{eyebrow?:string;title:string;body:string;action?:ReactNode}){return <div className="page-heading"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2><p>{body}</p></div>{action}</div>}
function Dashboard({go,openDeal}:{go:(s:Screen)=>void;openDeal:(d:Deal)=>void}){const metrics=[{l:"Active Deals",v:"12",d:"₹1.82 Cr under management",t:"+8.2%",i:Handshake},{l:"Pending Agreements",v:"04",d:"Awaiting confirmation",t:"2 urgent",i:FileCheck2},{l:"Upcoming Actions",v:"08",d:"Within the next 7 days",t:"₹16.4L",i:Clock3},{l:"Completed Deals",v:"37",d:"This financial year",t:"+12%",i:CheckCircle2}];return <><PageHeading eyebrow="SATURDAY, 12 SEPTEMBER" title="Good evening, Vertex Commerce" body="Here's what's happening across your active deals." action={<Button onClick={()=>go("new")}><Plus size={17}/>New Conversation</Button>}/><section className="action-grid"><Card className="action-card" onClick={()=>go("meeting")}><div className="action-card__icon"><Video/></div><div><span className="eyebrow">ONLINE</span><h3>Start a live conversation</h3><p>Meet with business parties while Armor identifies the terms being discussed.</p><span className="text-action">Start Online Meeting <ArrowRight size={16}/></span></div></Card><Card className="action-card" onClick={()=>go("recording")}><div className="action-card__icon action-card__icon--dark"><Mic/></div><div><span className="eyebrow">IN PERSON</span><h3>Capture an offline meeting</h3><p>Record an in-person conversation and turn it into a verifiable deal.</p><span className="text-action">Start Recording <ArrowRight size={16}/></span></div></Card></section><section><div className="section-title"><h3>Business overview</h3><span>Updated just now</span></div><div className="metrics">{metrics.map(({l,v,d,t,i:I})=><Card className="metric" key={l}><div className="metric__top"><span className="metric__icon"><I size={18}/></span><span className="trend">{t}</span></div><b>{v}</b><h4>{l}</h4><p>{d}</p></Card>)}</div></section><RecentDeals openDeal={openDeal}/></>}
function RecentDeals({openDeal}:{openDeal:(d:Deal)=>void}){return <section><div className="section-title"><div><h3>Recent deals</h3><span>Financial commitments requiring your attention</span></div><button>View all <ArrowRight size={15}/></button></div><div className="data-table"><div className="table-row table-head"><span>Deal</span><span>Counterparty</span><span>Value</span><span>Status</span><span>Next milestone</span><span>Progress</span></div>{deals.map(d=><button className="table-row" key={d.id} onClick={()=>openDeal(d)}><span><b>{d.id}</b><small>{d.title}</small></span><span>{d.counterparty}</span><span><b>{money(d.totalAmount)}</b></span><span><StatusBadge status={d.status}/></span><span>{d.nextMilestone}<small>{d.deadline}</small></span><span><Progress value={d.progress}/><small>{d.progress}%</small></span></button>)}</div></section>}
function NewConversation({go}:{go:(s:Screen)=>void}){return <><PageHeading eyebrow="CREATE" title="Start a Business Conversation" body="Capture the conversation and let Armor identify what both parties agreed to."/><div className="choice-grid"><button className="choice" onClick={()=>go("meeting")}><span className="choice__visual"><Video size={38}/><i/><i/></span><div><h3>Online Meeting</h3><p>Start a polished meeting space with live transcript capture and AI deal understanding.</p><span>Start Online Meeting <ArrowRight size={17}/></span></div></button><button className="choice" onClick={()=>go("recording")}><span className="choice__visual choice__visual--mic"><Mic size={38}/><i/><i/></span><div><h3>Offline Meeting</h3><p>Record an in-person business conversation and process it into structured terms.</p><span>Start Recording <ArrowRight size={17}/></span></div></button></div><div className="workflow-strip"><span>Conversation</span><ArrowRight/><span>Deal understanding</span><ArrowRight/><span>Verified agreement</span><ArrowRight/><span>Tracked obligations</span></div></>}
function Meeting({onEnd}:{onEnd:()=>void}){const [mic,setMic]=useState(true),[cam,setCam]=useState(true);return <div className="meeting"><div className="meeting-main"><div className="meeting-meta"><span className="live-dot"/>Recording <b>24:31</b><span>Secure conversation</span></div><div className="video-grid"><div className="video-tile video-tile--main"><div className="avatar-xl">RJ</div><span>Rahul Jain · Vertex Commerce</span><i><Mic size={14}/></i></div><div className="video-tile"><div className="avatar-xl avatar-xl--green">AM</div><span>Arjun Mehta · Shakti Components</span><i><Mic size={14}/></i></div></div><div className="meeting-controls"><IconButton label={mic?"Mute microphone":"Unmute microphone"} onClick={()=>setMic(!mic)}>{mic?<Mic/>:<MicOff/>}</IconButton><IconButton label={cam?"Turn camera off":"Turn camera on"} onClick={()=>setCam(!cam)}>{cam?<Camera/>:<VideoOff/>}</IconButton><IconButton label="Share screen"><ArrowRight/></IconButton><IconButton label="More options"><MoreHorizontal/></IconButton><IconButton label="End meeting" className="end-call" onClick={onEnd}><StopCircle/></IconButton></div></div><aside className="ai-panel"><div className="ai-panel__head"><span className="brand__mark"><Sparkles/></span><div><h3>ARMOR AI</h3><span><i/> Listening</span></div></div><div className="ai-insight"><ShieldCheck size={17}/><div><b>Deal signal detected</b><span>Supply agreement · 4 terms found</span></div></div><div className="transcript-live"><div className="section-title"><h3>Live transcript</h3><span>Auto-scroll on</span></div>{initialTranscript.map((t,i)=><div className="live-line" style={{animationDelay:`${i*120}ms`}} key={t.id}><span>{t.speaker}<time>{t.timestamp}</time></span><p>{t.text}</p></div>)}</div></aside></div>}
function Recording({go}:{go:(s:Screen)=>void}){const [state,setState]=useState<"ready"|"recording"|"paused"|"processing">("ready"),[seconds,setSeconds]=useState(0),[step,setStep]=useState(0);useEffect(()=>{if(state!=="recording")return;const id=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(id)},[state]);useEffect(()=>{if(state!=="processing")return;const id=setInterval(()=>setStep(s=>{if(s>=4){clearInterval(id);setTimeout(()=>go("transcript"),600);return s}return s+1}),650);return()=>clearInterval(id)},[state,go]);const time=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;const steps=["Uploading audio","Transcribing conversation","Identifying participants","Extracting financial terms","Preparing deal information"];return <><PageHeading eyebrow="OFFLINE CONVERSATION" title="Capture the agreement in the room" body="Armor will turn this recording into structured terms for your review."/><Card className="recorder">{state!=="processing"?<><div className={`mic-orbit ${state==="recording"?"recording":""}`}><Mic size={42}/><i/><i/></div><span className="recorder__status">{state==="ready"?"READY":state==="paused"?"PAUSED":"RECORDING"}</span><div className="timer">{time}</div><p>{state==="ready"?"Place your device near the conversation participants.":"Audio is being captured securely on this device."}</p><div className="recorder__buttons">{state==="ready"?<Button onClick={()=>setState("recording")}><Mic size={17}/>Start Recording</Button>:<><Button variant="secondary" onClick={()=>setState(state==="paused"?"recording":"paused")}>{state==="paused"?<Play size={17}/>:<Pause size={17}/>} {state==="paused"?"Resume":"Pause"}</Button><Button variant="danger" onClick={()=>setState("processing")}><StopCircle size={17}/>Stop & Process</Button></>}</div></>:<><span className="brand__mark brand__mark--large"><Sparkles/></span><h2>Understanding your conversation</h2><p>Armor is identifying the deal, not just transcribing the words.</p><div className="processing-list">{steps.map((s,i)=><div className={i<=step?"done":""} key={s}>{i<step?<Check/>:i===step?<span className="processing-ring"/>:<span>{i+1}</span>}<b>{s}</b></div>)}</div></>}</Card></>}
function TranscriptWorkspace({rows,setRows,go,notify}:{rows:Transcript[];setRows:(r:Transcript[])=>void;go:(s:Screen)=>void;notify:(s:string)=>void}){const [editing,setEditing]=useState<string|null>(null);const update=(id:string,text:string)=>setRows(rows.map(r=>r.id===id?{...r,text}:r));return <><PageHeading title="Conversation Transcript" body="Review and correct the conversation before Armor identifies the agreement." action={<span className="ai-badge"><Sparkles size={14}/>AI Generated</span>}/><div className="summary-bar"><span><CalendarDays/>12 Sep 2026<small>Meeting date</small></span><span><Clock3/>24 min 31 sec<small>Duration</small></span><span><Users/>2 participants<small>Participants</small></span><span><Video/>Online<small>Meeting type</small></span><span><CheckCircle2/>Complete<small>Recording</small></span></div><div className="transcript-layout"><Card className="transcript-editor"><div className="editor-toolbar"><div><IconButton label="Undo"><Undo2/></IconButton><IconButton label="Redo"><Redo2/></IconButton></div><div><IconButton label="Search transcript"><Search/></IconButton><IconButton label="Copy transcript" onClick={()=>notify("Transcript copied.")}><Copy/></IconButton></div></div>{rows.map((r,i)=><div className="transcript-row" key={r.id}><div className="speaker-avatar">{r.speaker.slice(0,1)}</div><div><div className="speaker-line"><b>{r.speaker}</b><time>{r.timestamp}</time><button onClick={()=>setEditing(editing===r.id?null:r.id)}><PenLine size={14}/>Edit</button></div>{editing===r.id?<textarea value={r.text} onChange={e=>update(r.id,e.target.value)} onBlur={()=>setEditing(null)} autoFocus/>:<p>{r.text}</p>}<span className="confidence"><Check size={12}/>{Math.round(r.confidence*100)}% confidence</span></div></div>)}</Card><aside className="review-panel"><h3>Review checklist</h3><p>Confirm the source conversation before analysis begins.</p>{["Participant names","Quantities and prices","Payment terms","Dates and deadlines"].map(s=><label key={s}><input type="checkbox" defaultChecked/><span><Check size={13}/></span>{s}</label>)}<div className="review-note"><ShieldCheck/><p>Your edits become the source of truth for deal analysis.</p></div><Button onClick={()=>go("analysis")}>Continue to Deal Analysis <ArrowRight size={17}/></Button></aside></div></>}
function Analysis({go,onResolve}:{go:(s:Screen)=>void;onResolve:()=>void}){const items=["Transcript processed","Participants identified","Financial terms detected","Deal conditions extracted","Responsibilities identified","Deadlines identified"];return <><PageHeading eyebrow="AI DEAL UNDERSTANDING" title="Armor found a supply agreement" body="Review every extracted term and verify ambiguity before creating the agreement."/><div className="analysis-grid"><Card className="analysis-progress"><h3>Analysis complete</h3><div className="step-list">{items.map(s=><div key={s}><CheckCircle2/><span>{s}</span><small>Verified</small></div>)}</div></Card><Card className="confidence-card"><span>Overall confidence</span><b>94%</b><Progress value={94}/><p>5 of 6 critical terms are confirmed directly by the transcript.</p></Card></div><Card className="alert-card"><AlertTriangle/><div><span className="eyebrow">CONFIRMATION REQUIRED</span><h3>Delivery date needs your review</h3><p>The conversation references two dates: <b>20 September</b> and <b>25 September</b>. Choose the agreed deadline before proceeding.</p></div><Button variant="secondary" onClick={onResolve}><AlertTriangle size={16}/>Resolve Issue</Button></Card><DealSummary/><div className="sticky-actions"><span><ShieldCheck/>1 term requires confirmation</span><Button onClick={()=>go("review")}>Create Editable Deal <ArrowRight size={16}/></Button></div></>}
function DealSummary(){return <Card className="deal-summary"><div className="summary-title"><div><span className="eyebrow">STRUCTURED DEAL</span><h3>500 Unit Supply Agreement</h3></div><span className="ai-badge"><Sparkles/>Extracted by Armor</span></div><div className="parties"><div><span>BUYER</span><b>Rahul Jain</b><p>Vertex Commerce</p></div><ArrowRight/><div><span>SELLER</span><b>Arjun Mehta</b><p>Shakti Components Pvt Ltd</p></div></div><div className="term-grid"><Term label="Product" value="Precision valve assemblies"/><Term label="Quantity" value="500 units"/><Term label="Unit price" value="₹800 / unit"/><Term label="Total amount" value="₹4,00,000" verified/><Term label="Delivery deadline" value="20 September 2026" verified/><Term label="Payment" value="30% advance" warning/></div><div className="payment-breakdown"><div><span>Advance · 30%</span><b>₹1,20,000</b></div><div><span>Balance · 70%</span><b>₹2,80,000</b></div><div className="payment-bar"><i/><i/></div></div><div className="responsibilities"><div><h4>Buyer responsibilities</h4><p><Check/>Pay ₹1,20,000 advance</p><p><Check/>Pay balance after delivery</p></div><div><h4>Seller responsibilities</h4><p><Check/>Provide 500 units</p><p><Check/>Deliver by 20 September</p></div></div></Card>}
function Term({label,value,verified,warning}:{label:string;value:string;verified?:boolean;warning?:boolean}){return <div className="term"><span>{label}</span><b>{value}</b>{(verified||warning)&&<small className={warning?"verify-warn":"verify-ok"}>{warning?<AlertTriangle/>:<CheckCircle2/>}{warning?"Needs confirmation":"Confirmed"}</small>}</div>}
function DealReview({go,notify}:{go:(s:Screen)=>void;notify:(s:string)=>void}){const [title,setTitle]=useState("500 Unit Supply Agreement"),[saved,setSaved]=useState(true),[notes,setNotes]=useState("Quality inspection will be completed at the delivery location.");const change=(f:(v:string)=>void)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>{f(e.target.value);setSaved(false);setTimeout(()=>setSaved(true),700)};return <><PageHeading title="Review Deal Agreement" body="Edit the structured terms. The agreement preview updates with your changes." action={<span className="save-state"><Check size={15}/>{saved?"Saved just now":"Saving..."}</span>}/><div className="editor-split"><div className="deal-form"><Card><div className="card-head"><h3>Deal information</h3><MoreHorizontal/></div><Field label="Deal title" value={title} onChange={change(setTitle)}/><div className="form-grid"><Field label="Buyer" defaultValue="Vertex Commerce"/><Field label="Seller" defaultValue="Shakti Components Pvt Ltd"/><Field label="Product / service" defaultValue="Precision valve assemblies"/><Field label="Quantity" defaultValue="500 units"/><Field label="Unit price" defaultValue="₹800"/><Field label="Total amount" defaultValue="₹4,00,000"/></div></Card><Card><div className="card-head"><h3>Payment & delivery</h3><button><Plus/>Add field</button></div><Field label="Payment terms" defaultValue="30% advance, 70% after delivery"/><Field label="Delivery terms" defaultValue="Delivery by 20 September 2026"/></Card><Card><div className="card-head"><h3>Additional notes</h3><button><Trash2/>Remove</button></div><textarea className="large-input" value={notes} onChange={change(setNotes)}/></Card></div><DocumentPreview title={title} notes={notes}/></div><div className="sticky-actions"><Button variant="secondary" onClick={()=>notify("Draft saved.")}><FileText size={16}/>Save Draft</Button><Button variant="success" onClick={()=>go("agreement")}><Check size={16}/>Confirm Agreement</Button></div></>}
function DocumentPreview({title,notes}:{title:string;notes:string}){return <aside className="document-wrap"><div className="document-label">LIVE AGREEMENT PREVIEW <span>PAGE 1 OF 2</span></div><article className="document"><div className="document__brand"><span className="brand__mark"><ShieldCheck/></span>ARMOR</div><span className="document__kicker">DEAL AGREEMENT · ARM-1029</span><h2>{title}</h2><p>This deal record documents the commercial terms confirmed by both parties following their business conversation.</p><hr/><h4>1. Parties</h4><p><b>Buyer:</b> Vertex Commerce<br/><b>Seller:</b> Shakti Components Pvt Ltd</p><h4>2. Financial terms</h4><div className="document-total"><span>Total deal value</span><b>₹4,00,000</b></div><p>30% advance payment of ₹1,20,000. Remaining ₹2,80,000 payable after delivery.</p><h4>3. Delivery</h4><p>500 precision valve assemblies delivered on or before 20 September 2026.</p><h4>4. Additional notes</h4><p>{notes}</p><footer>Generated from a verified business conversation. This record is not represented as a legally binding electronic signature.</footer></article></aside>}
function Agreement({go,onSend}:{go:(s:Screen)=>void;onSend:()=>void}){return <><PageHeading eyebrow="ARMOR DEAL AGREEMENT" title="500 Unit Supply Agreement" body="Deal ID ARM-1029 · Created 12 September 2026" action={<StatusBadge status="Awaiting Counterparty"/>}/><div className="agreement-layout"><div><DocumentPreview title="500 Unit Supply Agreement" notes="Quality inspection will be completed at the delivery location."/></div><aside><Card className="confirmation-card"><h3>Confirmation status</h3><div><span className="party-icon"><Building2/></span><p><b>Vertex Commerce</b><span>Party A · Buyer</span></p><span className="confirmed"><Check/>Confirmed</span></div><div><span className="party-icon"><Building2/></span><p><b>Shakti Components</b><span>Party B · Seller</span></p><span className="awaiting"><Clock3/>Awaiting</span></div><Button onClick={onSend}><Send/>Send Agreement</Button><Button variant="secondary" onClick={()=>go("counterparty")}><ArrowRight/>Open Counterparty View</Button></Card><Card className="secure-note"><LockKeyhole/><div><b>Secure verification</b><p>Each party reviews the same verified terms and records an independent confirmation.</p></div></Card></aside></div></>}
function SendModal({onClose,onSend}:{onClose:()=>void;onSend:()=>void}){const [loading,setLoading]=useState(false);return <Modal title="Send Agreement" description="Invite the counterparty to securely review and confirm the terms." onClose={onClose}><Field label="Counterparty email" icon={<Mail/>} defaultValue="agreements@shakticomponents.in"/><Field label="Email subject" defaultValue="Deal Agreement — ARM-1029"/><div className="email-preview"><span>EMAIL PREVIEW</span><p>Hello,</p><p>Following our recent business conversation, Armor has prepared the agreed deal terms for your review.</p><p>Please review the agreement and confirm the terms.</p><b>Deal ID: ARM-1029</b><button>View Agreement</button><p>Regards,<br/>Vertex Commerce via Armor</p></div><div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button loading={loading} onClick={()=>{setLoading(true);setTimeout(onSend,900)}}><Send/>Send Agreement</Button></div></Modal>}
function ResolveModal({onClose,onDone}:{onClose:()=>void;onDone:()=>void}){const [date,setDate]=useState("20 September 2026");return <Modal title="Resolve delivery date" description="Select the date both parties intended to confirm." onClose={onClose}><div className="radio-list">{["20 September 2026","25 September 2026"].map(d=><label className={date===d?"selected":""} key={d}><input type="radio" checked={date===d} onChange={()=>setDate(d)}/><span><b>{d}</b><small>Referenced at 02:11 in transcript</small></span>{date===d&&<Check/>}</label>)}</div><div className="modal-actions"><Button variant="secondary" onClick={onClose}>Ignore for now</Button><Button onClick={onDone}><Check/>Confirm Date</Button></div></Modal>}
